org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.233
neo_version_range=[21,)
loader_version_range=[1,)

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

jei_version=19.27.0.340
curios_version=9.5.1+1.21.1

mod_id=embers
mod_name=Embers: New Age
mod_license=MIT License
mod_version=1.21.1-1.0.0
mod_group_id=hu.zoldleo.embers
mod_authors=ZoldLeo
mod_description=Dwarven-style Magitech Mod